apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-rest-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-rest-api
  template:
    metadata:
      labels:
        app: go-rest-api
    spec:
      containers:
      - name: go-rest-api
        image: 206055865483.dkr.ecr.us-east-1.amazonaws.com/go-rest-api:latest
        ports:
        - containerPort: 8080
