apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-rest-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-rest-api
  template:
    metadata:
      labels:
        app: go-rest-api
    spec:
      containers:
      - name: go-rest-api
        image: gcr.io/[YOUR_GCP_PROJECT_ID]/go-rest-api:latest
        ports:
        - containerPort: 8080
